## ***Rview Machine Learning***
---

In this docuemnt we are going to focus on the review of some topics and examples about machine learning seen in class. The goal is create my own prediction model applying the topics studied previously.

### **Supervised learnign**
### **1. The classification**
---

In the classification is important that our data has already cleaned. we can't have *NaN, null or corrupt* values. Also is important apply the ***permutation***, to guarantee the data ramdomness

### **The Gaussian Naive Bayes**
---

#### **What is this?**
---
The gaussian naive bayes is a variant of the naive bayes algorithm used for clasification, when your input features are continuous and you assume that they follow a normal distribution.

#### **When to use the gaussian naive bayes**
---
We use the naussian naive bayes when we have:

- Small datasets
- Features roughly normally distributed
- Real-time predictions (very fast)
- Baseline classifier

In [1]:
#Import all our resources
import numpy as np
import pandas as pd

## Information about our dataset
---


| Column | Description |
| :--- | :--- |
| **job_title** | The job role or position (e.g., Data Analyst, AI Engineer) |
| **experience_years** | Number of years of professional experience |
| **education_level** | Highest level of education completed |
| **skills_count** | Number of technical or professional skills |
| **industry** | Industry sector where the job belongs |
| **company_size** | Size of the company (small, medium, large) |
| **location** | Job location or region |
| **remote_work** | Whether the job allows remote work |
| **certifications** | Number of professional certifications |
| **salary** | Annual salary of the employee |

### **We need to extract the X and Y(ground truth) columns**

In [2]:
df = pd.read_csv("jobSalaryDataset/job_salary_prediction_dataset.csv")
print(df.columns)
print("Min value: ", df["salary"].min())
print("Max Value: ",  df["salary"].max())

df.loc[(df["salary"] > 0) & (df['salary'] <= 75000), "Classification_salary"] = "Low"
df.loc[(df["salary"] > 75000) & (df['salary'] <= 100000), "Classification_salary"] = "Mid"
df.loc[(df["salary"] > 100000), "Classification_salary"] = "High"

df.head()

Index(['job_title', 'experience_years', 'education_level', 'skills_count',
       'industry', 'company_size', 'location', 'remote_work', 'certifications',
       'salary'],
      dtype='str')
Min value:  31867
Max Value:  333046

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary,Classification_salary
0,AI Engineer,10,Bachelor,2,Healthcare,Medium,India,Hybrid,2,109413,High
1,Data Analyst,5,Bachelor,17,Telecom,Small,Australia,No,0,93764,Mid
2,Frontend Developer,18,PhD,4,Media,Medium,Singapore,No,1,148123,High
3,Business Analyst,19,PhD,13,Retail,Medium,Canada,Yes,0,189123,High
4,Product Manager,15,Bachelor,7,Manufacturing,Large,Sweden,Yes,0,165069,High

In [3]:
X_values = df.loc[:,["experience_years", "skills_count", "company_size", "certifications"]]
y_values = df.loc[:,"Classification_salary"]

print(X_values.company_size.value_counts())
X_values["company_size"] = X_values["company_size"].replace({"Startup": 0, "Small": 1, "Medium": 2, "Large": 3, "Enterprise": 4})

X_values.head()

company_size
Large         50254
Small         50235
Medium        50027
Enterprise    49875
Startup       49609
Name: count, dtype: int64

   experience_years  skills_count company_size  certifications
0                10             2            2               2
1                 5            17            1               0
2                18             4            2               1
3                19            13            2               0
4                15             7            3               0

In [4]:
y_values.head()

0    High
1     Mid
2    High
3    High
4    High
Name: Classification_salary, dtype: str

#### **We need create the estimator,  and the train predict**
---
in this case we are going to use the gaussian naive bayes estimator
and the model selection cross_val_score to obtain a good permutation and keep the randomness.

In [5]:
#import resources from sklearn
from sklearn.naive_bayes import GaussianNB
#2 selection models
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

#test_validation => Percentage of the data for test, in this case is 0.3 i mean 30%
#random_state => Reproducible output across multiple function calls
#shuffle => We can use it to permutate the data before split, but in this application we are using random state and it's not necessary
X_train, X_test, Y_train, Y_test = train_test_split(X_values, y_values, test_size=0.3, random_state=21)

#We need to create our estimator
est = GaussianNB()

#We need to train our model
#to do this we use the fit function
est.fit(X_train,Y_train)

#Now we already to predict the future values, this function returns an array with the predicted values
preVal = est.predict(X_test)
print(preVal)

#Now we can select a metric to compare the results of the predict with the real values
print(accuracy_score(Y_test, preVal))

['High' 'High' 'High' ... 'High' 'High' 'High']
0.8955866666666666

Now we are goint to change the selection model for a cross validation

In [6]:
#before we have imported the cross_val_score
#This function returns an array where we cand found different valus of a metric
#our first parameter is the estimator = for us is the est with Gaussian naive bayes
#the second parameter is the data to fit, i mean X witout split.
#the third parameter is the data objetive, our ground truth y without split.

#We import the KFold to indicates how many iterations we want and if we want to shuffle the data before splitting.
from sklearn.model_selection import KFold
accuracys = cross_val_score(est, X_values, y_values, scoring='accuracy', cv=KFold(10, shuffle=True) )

print(accuracys)
print("Mean: ", np.mean(accuracys))
print("Standard desviation: ", np.std(accuracys))

[0.89784 0.8942  0.8962  0.89232 0.89332 0.8958  0.89416 0.89316 0.89324
 0.89628]
Mean:  0.894652
Standard desviation:  0.0016854245755891855

### **Now we are going to use others classificators**
* Decision Tree
* Random Forest
* support Vector Machine

# **Decision Tree**
---



# **Dataset:** Decisión para salir a jugar tenis

| Día | Clima | Viento | Humedad | ¿Jugar? |
|-----|-------|--------|---------|---------|
| 1   | Soleado | Débil | Alta | No |
| 2   | Soleado | Fuerte | Alta | No |
| 3   | Nublado | Débil | Alta | Sí |
| 4   | Lluvia | Débil | Alta | Sí |
| 5   | Lluvia | Débil | Normal | Sí |
| 6   | Lluvia | Fuerte | Normal | No |
| 7   | Nublado | Fuerte | Normal | Sí |
| 8   | Soleado | Débil | Normal | Sí |
| 9   | Soleado | Débil | Normal | Sí |
| 10  | Lluvia | Débil | Alta | No |

---


## Paso 1: Calcular la entropía inicial (desorden)
Esta es nuestra entropía general, la cual ocupa todo nuestro dataset siendo dividida por el número de clases dentro de nuestro ground truth.

**Fórmula de Entropía:** $H(S) = -\sum_{i=1}^{n} p_i \log_2(p_i)$

**Donde:**

**n =** Número de clases dentro de nuestro dataset

$p_i = P(\text{clase} = i) = \frac{\text{número de ejemplos de la clase } i}{\text{total de ejemplos}}$

**Clases:** Sí = 5, No = 5 (10 ejemplos)

$$
p_{\text{sí}} = \frac{5}{10} = 0.5, \quad p_{\text{no}} = \frac{5}{10} = 0.5
$$

$$
H(S) = -0.5 \cdot \log_2(0.5) - 0.5 \cdot \log_2(0.5) = -0.5 \cdot (-1) - 0.5 \cdot (-1) = 0.5 + 0.5 = 1
$$

**Entropía inicial = 1** (máximo desorden) -> No hay alguna clase dominante, si se sacara una muestra al azar no hay certeza de cual saldrá.

---

## Paso 2: Evaluar cada atributo (calcular Ganancia de Información)

**Fórmula:** $IG = H(S) - \sum \frac{|S_v|}{|S|} H(S_v)$

**Donde:**

$\frac{|S_v|}{|S|} = \frac{\text{número de ejemplos en } S_v}{\text{número total de ejemplos en } S}$

### Atributo 1: CLIMA

| Clima | Total | Sí | No | Entropía |
|-------|-------|----|----|----------|
| Soleado | 4 | 2 | 2 | $ -0.5\log_2(0.5)-0.5\log_2(0.5) = 1$ |
| Nublado | 2 | 2 | 0 | $ -1\log_2(1)-0 = 0 $ |
| Lluvia | 4 | 2 | 2 | $ 1 $ |

$$
H_{\text{clima}} = \frac{4}{10}(1) + \frac{2}{10}(0) + \frac{4}{10}(1) = 0.4 + 0 + 0.4 = 0.8
$$

$$
IG_{\text{clima}} = 1 - 0.8 = 0.2
$$

### Atributo 2: VIENTO

| Viento | Total | Sí | No | Entropía |
|--------|-------|----|----|----------|
| Débil | 6 | 4 | 2 | $ -0.667\log_2(0.667)-0.333\log_2(0.333) = 0.918 $ |
| Fuerte | 4 | 1 | 3 | $ -0.25\log_2(0.25)-0.75\log_2(0.75) = 0.811 $ |

$
H_{\text{viento}} = \frac{6}{10}(0.918) + \frac{4}{10}(0.811) = 0.55 + 0.324 = 0.874
$

$
IG_{\text{viento}} = 1 - 0.874 = 0.126
$

### Atributo 3: HUMEDAD

| Humedad | Total | Sí | No | Entropía |
|---------|-------|----|----|----------|
| Alta | 5 | 1 | 4 | $ -0.2\log_2(0.2)-0.8\log_2(0.8) = 0.722 $ |
| Normal | 5 | 4 | 1 | $ 0.722 $ |

$
H_{\text{humedad}} = \frac{5}{10}(0.722) + \frac{5}{10}(0.722) = 0.722
$

$
IG_{\text{humedad}} = 1 - 0.722 = 0.278
$

---

## Paso 3: Elegir el mejor atributo (mayor IG)

| Atributo | Ganancia de Información |
|----------|------------------------|
| Clima | 0.200 |
| Viento | 0.126 |
| **Humedad** | **0.278** ✓ |

**HUMEDAD** es la raíz del árbol.

---

## Paso 4: Construir el árbol

```
                    ¿Humedad?
                    /       \
                Alta        Normal
                /             \
            [1 Sí, 4 No]    [4 Sí, 1 No]
            Entropía=0.722   Entropía=0.722
```

### Rama Alta (5 ejemplos: 1 Sí, 4 No)

Analizamos subdataset:

| Clima | Sí | No | Entropía |
|-------|----|----|----------|
| Soleado | 0 | 2 | 0 |
| Nublado | 1 | 0 | 0 |
| Lluvia | 0 | 2 | 0 |

**Entropía = 0** (todos los subgrupos son puros) → **hoja con decisión NO**

### Rama Normal (5 ejemplos: 4 Sí, 1 No)

| Clima | Sí | No | Entropía |
|-------|----|----|----------|
| Soleado | 2 | 0 | 0 |
| Nublado | 1 | 0 | 0 |
| Lluvia | 1 | 1 | 1 |

Para Lluvia necesitamos otro nivel (por ejemplo, Viento)

---

## Árbol final:

```
                    HUMEDAD
                      |
        -------------------------
        |                       |
      Alta                   Normal
        |                       |
       NO                      CLIMA
                                |
                -------------------------
                |           |           |
            Soleado      Nublado       Lluvia
                |           |            |
               SÍ           SÍ          VIENTO
                                          |
                                    ------------
                                    |          |
                                  Débil      Fuerte
                                    |          |
                                    SÍ         NO
```

---

## Resumen del proceso:

1. **Calcular entropía** del nodo padre
2. **Calcular entropía ponderada** para cada atributo de cada feature
3. **Calcular Ganancia de Información** = Entropía(padre) - Entropía(atributo)
4. **Elegir el atributo con mayor IG** como nodo de división
5. **Repetir recursivamente** hasta que:
   - Todos los ejemplos sean de la misma clase (entropía = 0)
   - No queden atributos para dividir
   - Se alcance una profundidad máxima

# **Ejemplo de código para Decision Tree**
---

In [7]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import make_scorer
from sklearn.model_selection import KFold

est = DecisionTreeClassifier()

est.fit(X_train, Y_train)
predictions = est.predict(X_test)

acc = accuracy_score(Y_test, predictions)
print("Model Accuracy: ", acc)

for n in range(2, 11):
    est = DecisionTreeClassifier(max_depth=n)
    est.fit(X_train, Y_train)
    predictions = est.predict(X_test)
    s = cross_val_score(est, X_values, y_values, cv=KFold(10, shuffle=True), scoring=make_scorer(accuracy_score))

    print("\n\nMax depth = ", n)
    print("\nAccuracys for each Fold")
    print(s)
    print("\nAcuracy Mean: ", s.mean())
    print("Accuracy std: ", s.std())

Model Accuracy:  0.8940533333333334


Max depth =  2

Accuracys for each Fold
[0.89468 0.8924  0.89244 0.89628 0.89536 0.89604 0.89596 0.89864 0.8918
 0.89292]

Acuracy Mean:  0.894652
Accuracy std:  0.0020926576404180263


Max depth =  3

Accuracys for each Fold
[0.89332 0.89636 0.89516 0.89528 0.89476 0.8986  0.89064 0.89524 0.8952
 0.89196]

Acuracy Mean:  0.8946519999999998
Accuracy std:  0.0021197018658292485


Max depth =  4

Accuracys for each Fold
[0.89348 0.89524 0.89296 0.89428 0.8942  0.89468 0.89636 0.89496 0.89508
 0.89528]

Acuracy Mean:  0.894652
Accuracy std:  0.0009227870827011029


Max depth =  5

Accuracys for each Fold
[0.8968  0.89324 0.89564 0.89452 0.8936  0.89256 0.89516 0.8962  0.89392
 0.89488]

Acuracy Mean:  0.894652
Accuracy std:  0.0012777542799771782


Max depth =  6

Accuracys for each Fold
[0.89564 0.8944  0.89216 0.89496 0.89356 0.8986  0.89352 0.89552 0.89256
 0.8956 ]

Acuracy Mean:  0.894652
Accuracy std:  0.0017729568522668463


Max depth =  7

Accuracys for each Fold
[0.89256 0.89336 0.89628 0.89548 0.89392 0.89352 0.89468 0.89388 0.89712
 0.89572]

Acuracy Mean:  0.894652
Accuracy std:  0.0013793969696936342


Max depth =  8

Accuracys for each Fold
[0.89668 0.89212 0.89092 0.89424 0.89508 0.89392 0.89588 0.89748 0.895
 0.89512]

Acuracy Mean:  0.8946440000000001
Accuracy std:  0.0018757782384919582


Max depth =  9

Accuracys for each Fold
[0.89788 0.89212 0.89092 0.89492 0.89404 0.89504 0.89668 0.89632 0.89384
 0.89372]

Acuracy Mean:  0.8945480000000001
Accuracy std:  0.0019917469718817183


Max depth =  10

Accuracys for each Fold
[0.89596 0.8954  0.89272 0.89176 0.89576 0.89456 0.89532 0.8938  0.89308
 0.89508]

Acuracy Mean:  0.8943439999999999
Accuracy std:  0.001359435176828966

In [8]:
from sklearn.ensemble import RandomForestClassifier

est = RandomForestClassifier()

est.fit(X_train, Y_train)

predictions = est.predict(X_test)

acc = accuracy_score(Y_test, predictions)

print("Accuracy: ", acc)

Accuracy:  0.8933733333333334

In [9]:
from sklearn.svm import SVC

est = SVC()
est.fit(X_train, Y_train)
predictions =  est.predict(X_test)

acc = accuracy_score(Y_test, predictions)

In [10]:
print(acc)

0.8955866666666666

# **Deep Learning**

In [19]:
nc = len(np.unique(y_values))
print(nc)

X_train['company_size'] = pd.factorize(X_train['company_size'])[0]
X_test['company_size'] = pd.factorize(X_test['company_size'])[0]

Y_train = pd.factorize(Y_train)[0]
Y_test = pd.factorize(Y_test)[0]

3

In [ ]:
import tensorflow as tf
import keras



model = tf.keras.Sequential([
    tf.keras.layers.Dense(256, activation='relu'),
    tf.keras.layers.Dense(256, activation='relu'),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dense(3, activation='sigmoid')
])

model.compile(
    optimizer=tf.keras.optimizers.Adam(),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model.fit(X_train, Y_train, epochs=10)

test_loss, test_acc = model.evaluate(X_test, Y_test)

print("Loss: ", test_loss)
print("Accuracy: ", test_acc)

Epoch 1/10
5469/5469 ━━━━━━━━━━━━━━━━━━━━ 15s 3ms/step - accuracy: 0.8943 - loss: 0.3505
Epoch 2/10
5469/5469 ━━━━━━━━━━━━━━━━━━━━ 15s 3ms/step - accuracy: 0.8943 - loss: 0.3481
Epoch 3/10
5469/5469 ━━━━━━━━━━━━━━━━━━━━ 12s 2ms/step - accuracy: 0.8943 - loss: 0.3474
Epoch 4/10
5469/5469 ━━━━━━━━━━━━━━━━━━━━ 13s 2ms/step - accuracy: 0.8943 - loss: 0.3466
Epoch 5/10
5469/5469 ━━━━━━━━━━━━━━━━━━━━ 16s 3ms/step - accuracy: 0.8943 - loss: 0.3460
Epoch 6/10
5469/5469 ━━━━━━━━━━━━━━━━━━━━ 13s 2ms/step - accuracy: 0.8943 - loss: 0.3449
Epoch 7/10
5469/5469 ━━━━━━━━━━━━━━━━━━━━ 15s 3ms/step - accuracy: 0.8943 - loss: 0.3432
Epoch 8/10
5469/5469 ━━━━━━━━━━━━━━━━━━━━ 14s 3ms/step - accuracy: 0.8943 - loss: 0.3415
Epoch 9/10
5469/5469 ━━━━━━━━━━━━━━━━━━━━ 15s 3ms/step - accuracy: 0.8943 - loss: 0.3392
Epoch 10/10
5469/5469 ━━━━━━━━━━━━━━━━━━━━ 11s 2ms/step - accuracy: 0.8943 - loss: 0.3369
2344/2344 ━━━━━━━━━━━━━━━━━━━━ 6s 2ms/step - accuracy: 0.8956 - loss: 0.3402
Loss:  0.34019017219543457
Accuracy:  0.8955866694450378

In [24]:
del model

In [25]:
import tensorflow as tf
import keras



model = tf.keras.Sequential([
    tf.keras.layers.Dense(256, activation='relu'),
    tf.keras.layers.Dense(256, activation='relu'),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dense(3, activation='sigmoid')
])

model.compile(
    optimizer=tf.keras.optimizers.Adam(),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model.fit(X_train, Y_train, epochs=10)

test_loss, test_acc = model.evaluate(X_test, Y_test)

print("Loss: ", test_loss)
print("Accuracy: ", test_acc)

Epoch 1/10
5469/5469 ━━━━━━━━━━━━━━━━━━━━ 21s 3ms/step - accuracy: 0.8941 - loss: 0.3514
Epoch 2/10
5469/5469 ━━━━━━━━━━━━━━━━━━━━ 17s 3ms/step - accuracy: 0.8943 - loss: 0.3482
Epoch 3/10
5469/5469 ━━━━━━━━━━━━━━━━━━━━ 14s 3ms/step - accuracy: 0.8943 - loss: 0.3403
Epoch 4/10
5469/5469 ━━━━━━━━━━━━━━━━━━━━ 20s 4ms/step - accuracy: 0.8943 - loss: 0.3337
Epoch 5/10
5469/5469 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step - accuracy: 0.8943 - loss: 0.3330
Epoch 6/10
5469/5469 ━━━━━━━━━━━━━━━━━━━━ 20s 4ms/step - accuracy: 0.8943 - loss: 0.3326
Epoch 7/10
5469/5469 ━━━━━━━━━━━━━━━━━━━━ 17s 3ms/step - accuracy: 0.8943 - loss: 0.3322
Epoch 8/10
5469/5469 ━━━━━━━━━━━━━━━━━━━━ 17s 3ms/step - accuracy: 0.8943 - loss: 0.3321
Epoch 9/10
5469/5469 ━━━━━━━━━━━━━━━━━━━━ 16s 3ms/step - accuracy: 0.8942 - loss: 0.3317
Epoch 10/10
5469/5469 ━━━━━━━━━━━━━━━━━━━━ 17s 3ms/step - accuracy: 0.8942 - loss: 0.3318
2344/2344 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.8956 - loss: 0.3487
Loss:  0.34868019819259644
Accuracy:  0.8955866694450378